name: Hello Github Actions
on: [push]
jobs:
  HelloWorld:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Robota mamy kaca"
      - run: echo "running on ${{runner.os}}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: "ls -la"
      - run: "tree ./"
      
      
